# Generated by Django 4.2.1 on 2023-06-29 04:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('stories', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='story',
            old_name='project_id',
            new_name='project',
        ),
        migrations.RemoveField(
            model_name='story',
            name='details',
        ),
        migrations.RemoveField(
            model_name='story',
            name='members',
        ),
        migrations.AddField(
            model_name='story',
            name='assignee',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='story',
            name='description',
            field=models.TextField(default='No description'),
        ),
        migrations.AlterField(
            model_name='story',
            name='estimated_time',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='story',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='story',
            name='idScheduled',
            field=models.IntegerField(choices=[(1, 'Scheduled'), (2, 'Not Scheduled')], default=2),
        ),
        migrations.AlterField(
            model_name='story',
            name='status',
            field=models.IntegerField(choices=[(1, 'Not Started'), (2, 'Started'), (3, 'Finished'), (4, 'Delivered')], default=1),
        ),
    ]
