# Generated by Django 4.2.1 on 2023-06-29 07:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0002_rename_project_id_story_project_remove_story_details_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='story',
            old_name='idScheduled',
            new_name='is_scheduled',
        ),
    ]
