# Generated by Django 4.2.1 on 2023-06-29 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0003_rename_idscheduled_story_is_scheduled'),
    ]

    operations = [
        migrations.AlterField(
            model_name='story',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='story',
            name='estimated_time',
            field=models.IntegerField(),
        ),
    ]
