# Generated by Django 4.2.1 on 2023-06-28 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projecttag',
            name='is_manager',
        ),
        migrations.AddField(
            model_name='projecttag',
            name='role',
            field=models.IntegerField(choices=[(1, 'Project Manager'), (2, 'Project Member')], default=2),
        ),
    ]
