# Generated by Django 4.2.1 on 2023-06-28 07:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_remove_projecttag_is_manager_projecttag_role'),
    ]

    operations = [
        migrations.RenameField(
            model_name='projecttag',
            old_name='member',
            new_name='user',
        ),
    ]
