# Generated by Django 4.2.1 on 2023-06-28 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_rename_member_projecttag_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='project_name',
            new_name='title',
        ),
        migrations.AddField(
            model_name='project',
            name='description',
            field=models.TextField(default='No description provided'),
        ),
    ]
